"""Add approval fields to bookings

Revision ID: 81e21875364e
Revises: 65afdf458477
Create Date: 2026-07-05 10:47:45.118887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e21875364e'
down_revision = '65afdf458477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('target_comment')
        batch_op.drop_column('admin_comment')

    # ### end Alembic commands ###
