"""Sync all models - add missing columns

Revision ID: 99188a7347bc
Revises: 
Create Date: 2026-07-04 15:03:11.481350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99188a7347bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
